name: Python CI

on:
  push:
    branches:
      - main # 當程式碼推送到 main 分支時觸發

jobs:
  build:
    runs-on: ubuntu-latest # 在 Ubuntu 最新版本上運行

    steps:
    - name: 簽出程式碼 # 獲取儲存庫的程式碼
      uses: actions/checkout@v4

    - name: 設定 Python 環境 # 設定 Python 版本
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' # 指定使用的 Python 版本

    - name: 安裝專案依賴 # 安裝 requirements.txt 中定義的所有依賴套件
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: 執行程式碼風格檢查 # 使用 flake8 檢查程式碼風格
      run: |
        flake8 .
